// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forumthread.proto

package com.ikai.protodemo.proto;

public final class ForumThreadProtos {
  private ForumThreadProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PostOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string title = 1;
    boolean hasTitle();
    String getTitle();
    
    // required int32 id = 2;
    boolean hasId();
    int getId();
    
    // required string body = 3;
    boolean hasBody();
    String getBody();
    
    // required int64 timestamp = 4;
    boolean hasTimestamp();
    long getTimestamp();
    
    // repeated .protodemo.Post reply = 5;
    java.util.List<com.ikai.protodemo.proto.ForumThreadProtos.Post> 
        getReplyList();
    com.ikai.protodemo.proto.ForumThreadProtos.Post getReply(int index);
    int getReplyCount();
    java.util.List<? extends com.ikai.protodemo.proto.ForumThreadProtos.PostOrBuilder> 
        getReplyOrBuilderList();
    com.ikai.protodemo.proto.ForumThreadProtos.PostOrBuilder getReplyOrBuilder(
        int index);
  }
  public static final class Post extends
      com.google.protobuf.GeneratedMessage
      implements PostOrBuilder {
    // Use Post.newBuilder() to construct.
    private Post(Builder builder) {
      super(builder);
    }
    private Post(boolean noInit) {}
    
    private static final Post defaultInstance;
    public static Post getDefaultInstance() {
      return defaultInstance;
    }
    
    public Post getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ikai.protodemo.proto.ForumThreadProtos.internal_static_protodemo_Post_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ikai.protodemo.proto.ForumThreadProtos.internal_static_protodemo_Post_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string title = 1;
    public static final int TITLE_FIELD_NUMBER = 1;
    private java.lang.Object title_;
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          title_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getId() {
      return id_;
    }
    
    // required string body = 3;
    public static final int BODY_FIELD_NUMBER = 3;
    private java.lang.Object body_;
    public boolean hasBody() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          body_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int64 timestamp = 4;
    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getTimestamp() {
      return timestamp_;
    }
    
    // repeated .protodemo.Post reply = 5;
    public static final int REPLY_FIELD_NUMBER = 5;
    private java.util.List<com.ikai.protodemo.proto.ForumThreadProtos.Post> reply_;
    public java.util.List<com.ikai.protodemo.proto.ForumThreadProtos.Post> getReplyList() {
      return reply_;
    }
    public java.util.List<? extends com.ikai.protodemo.proto.ForumThreadProtos.PostOrBuilder> 
        getReplyOrBuilderList() {
      return reply_;
    }
    public int getReplyCount() {
      return reply_.size();
    }
    public com.ikai.protodemo.proto.ForumThreadProtos.Post getReply(int index) {
      return reply_.get(index);
    }
    public com.ikai.protodemo.proto.ForumThreadProtos.PostOrBuilder getReplyOrBuilder(
        int index) {
      return reply_.get(index);
    }
    
    private void initFields() {
      title_ = "";
      id_ = 0;
      body_ = "";
      timestamp_ = 0L;
      reply_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBody()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getReplyCount(); i++) {
        if (!getReply(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTitleBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getBodyBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, timestamp_);
      }
      for (int i = 0; i < reply_.size(); i++) {
        output.writeMessage(5, reply_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTitleBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getBodyBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, timestamp_);
      }
      for (int i = 0; i < reply_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, reply_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.ikai.protodemo.proto.ForumThreadProtos.Post parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ikai.protodemo.proto.ForumThreadProtos.Post parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ikai.protodemo.proto.ForumThreadProtos.Post parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ikai.protodemo.proto.ForumThreadProtos.Post parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ikai.protodemo.proto.ForumThreadProtos.Post parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ikai.protodemo.proto.ForumThreadProtos.Post parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.ikai.protodemo.proto.ForumThreadProtos.Post parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ikai.protodemo.proto.ForumThreadProtos.Post parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ikai.protodemo.proto.ForumThreadProtos.Post parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ikai.protodemo.proto.ForumThreadProtos.Post parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ikai.protodemo.proto.ForumThreadProtos.Post prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ikai.protodemo.proto.ForumThreadProtos.PostOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ikai.protodemo.proto.ForumThreadProtos.internal_static_protodemo_Post_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ikai.protodemo.proto.ForumThreadProtos.internal_static_protodemo_Post_fieldAccessorTable;
      }
      
      // Construct using com.ikai.protodemo.proto.ForumThreadProtos.Post.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getReplyFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        body_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (replyBuilder_ == null) {
          reply_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          replyBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ikai.protodemo.proto.ForumThreadProtos.Post.getDescriptor();
      }
      
      public com.ikai.protodemo.proto.ForumThreadProtos.Post getDefaultInstanceForType() {
        return com.ikai.protodemo.proto.ForumThreadProtos.Post.getDefaultInstance();
      }
      
      public com.ikai.protodemo.proto.ForumThreadProtos.Post build() {
        com.ikai.protodemo.proto.ForumThreadProtos.Post result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.ikai.protodemo.proto.ForumThreadProtos.Post buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.ikai.protodemo.proto.ForumThreadProtos.Post result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.ikai.protodemo.proto.ForumThreadProtos.Post buildPartial() {
        com.ikai.protodemo.proto.ForumThreadProtos.Post result = new com.ikai.protodemo.proto.ForumThreadProtos.Post(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.body_ = body_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.timestamp_ = timestamp_;
        if (replyBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            reply_ = java.util.Collections.unmodifiableList(reply_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.reply_ = reply_;
        } else {
          result.reply_ = replyBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ikai.protodemo.proto.ForumThreadProtos.Post) {
          return mergeFrom((com.ikai.protodemo.proto.ForumThreadProtos.Post)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.ikai.protodemo.proto.ForumThreadProtos.Post other) {
        if (other == com.ikai.protodemo.proto.ForumThreadProtos.Post.getDefaultInstance()) return this;
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasBody()) {
          setBody(other.getBody());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (replyBuilder_ == null) {
          if (!other.reply_.isEmpty()) {
            if (reply_.isEmpty()) {
              reply_ = other.reply_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureReplyIsMutable();
              reply_.addAll(other.reply_);
            }
            onChanged();
          }
        } else {
          if (!other.reply_.isEmpty()) {
            if (replyBuilder_.isEmpty()) {
              replyBuilder_.dispose();
              replyBuilder_ = null;
              reply_ = other.reply_;
              bitField0_ = (bitField0_ & ~0x00000010);
              replyBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getReplyFieldBuilder() : null;
            } else {
              replyBuilder_.addAllMessages(other.reply_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTitle()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        if (!hasBody()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        for (int i = 0; i < getReplyCount(); i++) {
          if (!getReply(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              title_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              body_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              timestamp_ = input.readInt64();
              break;
            }
            case 42: {
              com.ikai.protodemo.proto.ForumThreadProtos.Post.Builder subBuilder = com.ikai.protodemo.proto.ForumThreadProtos.Post.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addReply(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string title = 1;
      private java.lang.Object title_ = "";
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTitle(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        title_ = value;
        onChanged();
        return this;
      }
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      void setTitle(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        title_ = value;
        onChanged();
      }
      
      // required int32 id = 2;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // required string body = 3;
      private java.lang.Object body_ = "";
      public boolean hasBody() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          body_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setBody(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        body_ = value;
        onChanged();
        return this;
      }
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000004);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      void setBody(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        body_ = value;
        onChanged();
      }
      
      // required int64 timestamp = 4;
      private long timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000008;
        timestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      
      // repeated .protodemo.Post reply = 5;
      private java.util.List<com.ikai.protodemo.proto.ForumThreadProtos.Post> reply_ =
        java.util.Collections.emptyList();
      private void ensureReplyIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          reply_ = new java.util.ArrayList<com.ikai.protodemo.proto.ForumThreadProtos.Post>(reply_);
          bitField0_ |= 0x00000010;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.ikai.protodemo.proto.ForumThreadProtos.Post, com.ikai.protodemo.proto.ForumThreadProtos.Post.Builder, com.ikai.protodemo.proto.ForumThreadProtos.PostOrBuilder> replyBuilder_;
      
      public java.util.List<com.ikai.protodemo.proto.ForumThreadProtos.Post> getReplyList() {
        if (replyBuilder_ == null) {
          return java.util.Collections.unmodifiableList(reply_);
        } else {
          return replyBuilder_.getMessageList();
        }
      }
      public int getReplyCount() {
        if (replyBuilder_ == null) {
          return reply_.size();
        } else {
          return replyBuilder_.getCount();
        }
      }
      public com.ikai.protodemo.proto.ForumThreadProtos.Post getReply(int index) {
        if (replyBuilder_ == null) {
          return reply_.get(index);
        } else {
          return replyBuilder_.getMessage(index);
        }
      }
      public Builder setReply(
          int index, com.ikai.protodemo.proto.ForumThreadProtos.Post value) {
        if (replyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReplyIsMutable();
          reply_.set(index, value);
          onChanged();
        } else {
          replyBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setReply(
          int index, com.ikai.protodemo.proto.ForumThreadProtos.Post.Builder builderForValue) {
        if (replyBuilder_ == null) {
          ensureReplyIsMutable();
          reply_.set(index, builderForValue.build());
          onChanged();
        } else {
          replyBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addReply(com.ikai.protodemo.proto.ForumThreadProtos.Post value) {
        if (replyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReplyIsMutable();
          reply_.add(value);
          onChanged();
        } else {
          replyBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addReply(
          int index, com.ikai.protodemo.proto.ForumThreadProtos.Post value) {
        if (replyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReplyIsMutable();
          reply_.add(index, value);
          onChanged();
        } else {
          replyBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addReply(
          com.ikai.protodemo.proto.ForumThreadProtos.Post.Builder builderForValue) {
        if (replyBuilder_ == null) {
          ensureReplyIsMutable();
          reply_.add(builderForValue.build());
          onChanged();
        } else {
          replyBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addReply(
          int index, com.ikai.protodemo.proto.ForumThreadProtos.Post.Builder builderForValue) {
        if (replyBuilder_ == null) {
          ensureReplyIsMutable();
          reply_.add(index, builderForValue.build());
          onChanged();
        } else {
          replyBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllReply(
          java.lang.Iterable<? extends com.ikai.protodemo.proto.ForumThreadProtos.Post> values) {
        if (replyBuilder_ == null) {
          ensureReplyIsMutable();
          super.addAll(values, reply_);
          onChanged();
        } else {
          replyBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearReply() {
        if (replyBuilder_ == null) {
          reply_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          replyBuilder_.clear();
        }
        return this;
      }
      public Builder removeReply(int index) {
        if (replyBuilder_ == null) {
          ensureReplyIsMutable();
          reply_.remove(index);
          onChanged();
        } else {
          replyBuilder_.remove(index);
        }
        return this;
      }
      public com.ikai.protodemo.proto.ForumThreadProtos.Post.Builder getReplyBuilder(
          int index) {
        return getReplyFieldBuilder().getBuilder(index);
      }
      public com.ikai.protodemo.proto.ForumThreadProtos.PostOrBuilder getReplyOrBuilder(
          int index) {
        if (replyBuilder_ == null) {
          return reply_.get(index);  } else {
          return replyBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.ikai.protodemo.proto.ForumThreadProtos.PostOrBuilder> 
           getReplyOrBuilderList() {
        if (replyBuilder_ != null) {
          return replyBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(reply_);
        }
      }
      public com.ikai.protodemo.proto.ForumThreadProtos.Post.Builder addReplyBuilder() {
        return getReplyFieldBuilder().addBuilder(
            com.ikai.protodemo.proto.ForumThreadProtos.Post.getDefaultInstance());
      }
      public com.ikai.protodemo.proto.ForumThreadProtos.Post.Builder addReplyBuilder(
          int index) {
        return getReplyFieldBuilder().addBuilder(
            index, com.ikai.protodemo.proto.ForumThreadProtos.Post.getDefaultInstance());
      }
      public java.util.List<com.ikai.protodemo.proto.ForumThreadProtos.Post.Builder> 
           getReplyBuilderList() {
        return getReplyFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.ikai.protodemo.proto.ForumThreadProtos.Post, com.ikai.protodemo.proto.ForumThreadProtos.Post.Builder, com.ikai.protodemo.proto.ForumThreadProtos.PostOrBuilder> 
          getReplyFieldBuilder() {
        if (replyBuilder_ == null) {
          replyBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.ikai.protodemo.proto.ForumThreadProtos.Post, com.ikai.protodemo.proto.ForumThreadProtos.Post.Builder, com.ikai.protodemo.proto.ForumThreadProtos.PostOrBuilder>(
                  reply_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          reply_ = null;
        }
        return replyBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:protodemo.Post)
    }
    
    static {
      defaultInstance = new Post(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protodemo.Post)
  }
  
  public interface ForumThreadOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .protodemo.Post post = 1;
    java.util.List<com.ikai.protodemo.proto.ForumThreadProtos.Post> 
        getPostList();
    com.ikai.protodemo.proto.ForumThreadProtos.Post getPost(int index);
    int getPostCount();
    java.util.List<? extends com.ikai.protodemo.proto.ForumThreadProtos.PostOrBuilder> 
        getPostOrBuilderList();
    com.ikai.protodemo.proto.ForumThreadProtos.PostOrBuilder getPostOrBuilder(
        int index);
  }
  public static final class ForumThread extends
      com.google.protobuf.GeneratedMessage
      implements ForumThreadOrBuilder {
    // Use ForumThread.newBuilder() to construct.
    private ForumThread(Builder builder) {
      super(builder);
    }
    private ForumThread(boolean noInit) {}
    
    private static final ForumThread defaultInstance;
    public static ForumThread getDefaultInstance() {
      return defaultInstance;
    }
    
    public ForumThread getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ikai.protodemo.proto.ForumThreadProtos.internal_static_protodemo_ForumThread_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ikai.protodemo.proto.ForumThreadProtos.internal_static_protodemo_ForumThread_fieldAccessorTable;
    }
    
    // repeated .protodemo.Post post = 1;
    public static final int POST_FIELD_NUMBER = 1;
    private java.util.List<com.ikai.protodemo.proto.ForumThreadProtos.Post> post_;
    public java.util.List<com.ikai.protodemo.proto.ForumThreadProtos.Post> getPostList() {
      return post_;
    }
    public java.util.List<? extends com.ikai.protodemo.proto.ForumThreadProtos.PostOrBuilder> 
        getPostOrBuilderList() {
      return post_;
    }
    public int getPostCount() {
      return post_.size();
    }
    public com.ikai.protodemo.proto.ForumThreadProtos.Post getPost(int index) {
      return post_.get(index);
    }
    public com.ikai.protodemo.proto.ForumThreadProtos.PostOrBuilder getPostOrBuilder(
        int index) {
      return post_.get(index);
    }
    
    private void initFields() {
      post_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getPostCount(); i++) {
        if (!getPost(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < post_.size(); i++) {
        output.writeMessage(1, post_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < post_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, post_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.ikai.protodemo.proto.ForumThreadProtos.ForumThread parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ikai.protodemo.proto.ForumThreadProtos.ForumThread parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ikai.protodemo.proto.ForumThreadProtos.ForumThread parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ikai.protodemo.proto.ForumThreadProtos.ForumThread parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ikai.protodemo.proto.ForumThreadProtos.ForumThread parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ikai.protodemo.proto.ForumThreadProtos.ForumThread parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.ikai.protodemo.proto.ForumThreadProtos.ForumThread parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ikai.protodemo.proto.ForumThreadProtos.ForumThread parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ikai.protodemo.proto.ForumThreadProtos.ForumThread parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ikai.protodemo.proto.ForumThreadProtos.ForumThread parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ikai.protodemo.proto.ForumThreadProtos.ForumThread prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ikai.protodemo.proto.ForumThreadProtos.ForumThreadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ikai.protodemo.proto.ForumThreadProtos.internal_static_protodemo_ForumThread_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ikai.protodemo.proto.ForumThreadProtos.internal_static_protodemo_ForumThread_fieldAccessorTable;
      }
      
      // Construct using com.ikai.protodemo.proto.ForumThreadProtos.ForumThread.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPostFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (postBuilder_ == null) {
          post_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          postBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ikai.protodemo.proto.ForumThreadProtos.ForumThread.getDescriptor();
      }
      
      public com.ikai.protodemo.proto.ForumThreadProtos.ForumThread getDefaultInstanceForType() {
        return com.ikai.protodemo.proto.ForumThreadProtos.ForumThread.getDefaultInstance();
      }
      
      public com.ikai.protodemo.proto.ForumThreadProtos.ForumThread build() {
        com.ikai.protodemo.proto.ForumThreadProtos.ForumThread result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.ikai.protodemo.proto.ForumThreadProtos.ForumThread buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.ikai.protodemo.proto.ForumThreadProtos.ForumThread result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.ikai.protodemo.proto.ForumThreadProtos.ForumThread buildPartial() {
        com.ikai.protodemo.proto.ForumThreadProtos.ForumThread result = new com.ikai.protodemo.proto.ForumThreadProtos.ForumThread(this);
        int from_bitField0_ = bitField0_;
        if (postBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            post_ = java.util.Collections.unmodifiableList(post_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.post_ = post_;
        } else {
          result.post_ = postBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ikai.protodemo.proto.ForumThreadProtos.ForumThread) {
          return mergeFrom((com.ikai.protodemo.proto.ForumThreadProtos.ForumThread)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.ikai.protodemo.proto.ForumThreadProtos.ForumThread other) {
        if (other == com.ikai.protodemo.proto.ForumThreadProtos.ForumThread.getDefaultInstance()) return this;
        if (postBuilder_ == null) {
          if (!other.post_.isEmpty()) {
            if (post_.isEmpty()) {
              post_ = other.post_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePostIsMutable();
              post_.addAll(other.post_);
            }
            onChanged();
          }
        } else {
          if (!other.post_.isEmpty()) {
            if (postBuilder_.isEmpty()) {
              postBuilder_.dispose();
              postBuilder_ = null;
              post_ = other.post_;
              bitField0_ = (bitField0_ & ~0x00000001);
              postBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPostFieldBuilder() : null;
            } else {
              postBuilder_.addAllMessages(other.post_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getPostCount(); i++) {
          if (!getPost(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.ikai.protodemo.proto.ForumThreadProtos.Post.Builder subBuilder = com.ikai.protodemo.proto.ForumThreadProtos.Post.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPost(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .protodemo.Post post = 1;
      private java.util.List<com.ikai.protodemo.proto.ForumThreadProtos.Post> post_ =
        java.util.Collections.emptyList();
      private void ensurePostIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          post_ = new java.util.ArrayList<com.ikai.protodemo.proto.ForumThreadProtos.Post>(post_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.ikai.protodemo.proto.ForumThreadProtos.Post, com.ikai.protodemo.proto.ForumThreadProtos.Post.Builder, com.ikai.protodemo.proto.ForumThreadProtos.PostOrBuilder> postBuilder_;
      
      public java.util.List<com.ikai.protodemo.proto.ForumThreadProtos.Post> getPostList() {
        if (postBuilder_ == null) {
          return java.util.Collections.unmodifiableList(post_);
        } else {
          return postBuilder_.getMessageList();
        }
      }
      public int getPostCount() {
        if (postBuilder_ == null) {
          return post_.size();
        } else {
          return postBuilder_.getCount();
        }
      }
      public com.ikai.protodemo.proto.ForumThreadProtos.Post getPost(int index) {
        if (postBuilder_ == null) {
          return post_.get(index);
        } else {
          return postBuilder_.getMessage(index);
        }
      }
      public Builder setPost(
          int index, com.ikai.protodemo.proto.ForumThreadProtos.Post value) {
        if (postBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePostIsMutable();
          post_.set(index, value);
          onChanged();
        } else {
          postBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setPost(
          int index, com.ikai.protodemo.proto.ForumThreadProtos.Post.Builder builderForValue) {
        if (postBuilder_ == null) {
          ensurePostIsMutable();
          post_.set(index, builderForValue.build());
          onChanged();
        } else {
          postBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addPost(com.ikai.protodemo.proto.ForumThreadProtos.Post value) {
        if (postBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePostIsMutable();
          post_.add(value);
          onChanged();
        } else {
          postBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addPost(
          int index, com.ikai.protodemo.proto.ForumThreadProtos.Post value) {
        if (postBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePostIsMutable();
          post_.add(index, value);
          onChanged();
        } else {
          postBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addPost(
          com.ikai.protodemo.proto.ForumThreadProtos.Post.Builder builderForValue) {
        if (postBuilder_ == null) {
          ensurePostIsMutable();
          post_.add(builderForValue.build());
          onChanged();
        } else {
          postBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addPost(
          int index, com.ikai.protodemo.proto.ForumThreadProtos.Post.Builder builderForValue) {
        if (postBuilder_ == null) {
          ensurePostIsMutable();
          post_.add(index, builderForValue.build());
          onChanged();
        } else {
          postBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllPost(
          java.lang.Iterable<? extends com.ikai.protodemo.proto.ForumThreadProtos.Post> values) {
        if (postBuilder_ == null) {
          ensurePostIsMutable();
          super.addAll(values, post_);
          onChanged();
        } else {
          postBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearPost() {
        if (postBuilder_ == null) {
          post_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          postBuilder_.clear();
        }
        return this;
      }
      public Builder removePost(int index) {
        if (postBuilder_ == null) {
          ensurePostIsMutable();
          post_.remove(index);
          onChanged();
        } else {
          postBuilder_.remove(index);
        }
        return this;
      }
      public com.ikai.protodemo.proto.ForumThreadProtos.Post.Builder getPostBuilder(
          int index) {
        return getPostFieldBuilder().getBuilder(index);
      }
      public com.ikai.protodemo.proto.ForumThreadProtos.PostOrBuilder getPostOrBuilder(
          int index) {
        if (postBuilder_ == null) {
          return post_.get(index);  } else {
          return postBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.ikai.protodemo.proto.ForumThreadProtos.PostOrBuilder> 
           getPostOrBuilderList() {
        if (postBuilder_ != null) {
          return postBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(post_);
        }
      }
      public com.ikai.protodemo.proto.ForumThreadProtos.Post.Builder addPostBuilder() {
        return getPostFieldBuilder().addBuilder(
            com.ikai.protodemo.proto.ForumThreadProtos.Post.getDefaultInstance());
      }
      public com.ikai.protodemo.proto.ForumThreadProtos.Post.Builder addPostBuilder(
          int index) {
        return getPostFieldBuilder().addBuilder(
            index, com.ikai.protodemo.proto.ForumThreadProtos.Post.getDefaultInstance());
      }
      public java.util.List<com.ikai.protodemo.proto.ForumThreadProtos.Post.Builder> 
           getPostBuilderList() {
        return getPostFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.ikai.protodemo.proto.ForumThreadProtos.Post, com.ikai.protodemo.proto.ForumThreadProtos.Post.Builder, com.ikai.protodemo.proto.ForumThreadProtos.PostOrBuilder> 
          getPostFieldBuilder() {
        if (postBuilder_ == null) {
          postBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.ikai.protodemo.proto.ForumThreadProtos.Post, com.ikai.protodemo.proto.ForumThreadProtos.Post.Builder, com.ikai.protodemo.proto.ForumThreadProtos.PostOrBuilder>(
                  post_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          post_ = null;
        }
        return postBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:protodemo.ForumThread)
    }
    
    static {
      defaultInstance = new ForumThread(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protodemo.ForumThread)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protodemo_Post_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protodemo_Post_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protodemo_ForumThread_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protodemo_ForumThread_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021forumthread.proto\022\tprotodemo\"b\n\004Post\022\r" +
      "\n\005title\030\001 \002(\t\022\n\n\002id\030\002 \002(\005\022\014\n\004body\030\003 \002(\t\022" +
      "\021\n\ttimestamp\030\004 \002(\003\022\036\n\005reply\030\005 \003(\0132\017.prot" +
      "odemo.Post\",\n\013ForumThread\022\035\n\004post\030\001 \003(\0132" +
      "\017.protodemo.PostB-\n\030com.ikai.protodemo.p" +
      "rotoB\021ForumThreadProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protodemo_Post_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protodemo_Post_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protodemo_Post_descriptor,
              new java.lang.String[] { "Title", "Id", "Body", "Timestamp", "Reply", },
              com.ikai.protodemo.proto.ForumThreadProtos.Post.class,
              com.ikai.protodemo.proto.ForumThreadProtos.Post.Builder.class);
          internal_static_protodemo_ForumThread_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protodemo_ForumThread_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protodemo_ForumThread_descriptor,
              new java.lang.String[] { "Post", },
              com.ikai.protodemo.proto.ForumThreadProtos.ForumThread.class,
              com.ikai.protodemo.proto.ForumThreadProtos.ForumThread.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
